### ISSUE TITLE
Google.Protobuf 3.15.0 breaks the Otlp Exporter

### ISSUE THREAD

**Issue by EraYaN** [open-telemetry/opentelemetry-dotnet#1854]
# Bug Report

A bug report is not really the right way to report this one, this is more a heads up I guess if this ever manifests when updating the dependencies.

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 0.4.0-beta.2`): 

* `<PackageReference Include="OpenTelemetry" Version="1.0.1" />`
* `<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.0.1" />`
* `<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.0.1" />`

Runtime version:

* `net5.0`

## Symptom

Upgrading Google.Protobuf 3.14.0 -> 3.15.0 breaks the Otlp (Batch?) Exporter.

**What is the expected behavior?**

No exception. (So it finds the ByteString constructor)

**What is the actual behavior?**

The application crashes with this exception.

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.ActivityExtensions' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'con')
 at System.Reflection.Emit.DynamicILGenerator.Emit(OpCode opcode, ConstructorInfo con)
 at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.ActivityExtensions.CreateByteStringCtorFunc()
 at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.ActivityExtensions..cctor()
 --- End of inner exception stack trace ---
 at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.ActivityExtensions.AddBatch(ExportTraceServiceRequest request, Resource processResource, Batch`1& activityBatch)
 at OpenTelemetry.Exporter.OtlpTraceExporter.Export(Batch`1& activityBatch)
 at OpenTelemetry.BatchExportProcessor`1.ExporterProc()
 at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
 at System.Threading.ThreadHelper.ThreadStart()
```

## Reproduce

Update your application to Google.Protobuf 3.15.0 (local to the project)

## Additional Context

The new Google.Protobuf 3.15.0 package changed the ByteString type thus breaking compat with this package it seems.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ActivityExtensions.cs#L346 (here)

https://github.com/protocolbuffers/protobuf/pull/7645

**Comment by pereiren** [comment]
Hi guys, I faced this issue today. 

Is there any ETA for the release including this fix?

Thank you and best regards from Spain!

**Comment by cijothomas** [comment]
It'll be part of 1.1.0-beta2 release and being released today.
