### ISSUE TITLE
How to send traces to an Otel Collector running in OpenShift

### ISSUE THREAD

**Issue by notcool11** [open-telemetry/opentelemetry-dotnet#2071]
# I have the Otel Collector installed in OpenShift. Currently able to use Jaeger to send Http Thrift formatted traces without issue. Attempting to use the dotnet libraries and can see that traces are being generated, but unable to send to send the traces to OpenShift.

**Describe your environment.**
OpenShift Version: v3.11.404
Kubernetes Master: v1.11.0+d4cacc0
Otel Collector: splunk-otel-collector:0.21.1

Running code example: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/Console/TestOtlpExporter.cs

The code example is on my local machine and the Otel Collector is running in OpenShift.

**Describe any aspect of your environment relevant to the question.**
From the compliance metric, the only supported protocols are OTLP over GRPC and Jaeger over UDP:
https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#exporters

This is problematic because the HAProxy for OpenShift does not support HTTP2 and therefore doesn't support GRPC. Also, exposing anything besides and HTTP Route for OpenShift is not easy, so getting an open UDP port to send Jaeger formatted traces is not much of an option either.

We have a very diverse environment with dev laptops (windows and mac), win servers, linux servers and an On-Prem Cloud environment build on OpenShift. Ideally we would have a single Collector for all the trace data to flow through.

**What are you trying to achieve?**
Trying to run the above example on my local machine and send traces to a remote instance of the Otel Collector running in OpenShift. While possible to have hundreds of instances of the Otel Collector installed throughout the company, this is not desirable.

**What did you expect to see?**
Expected to see my trace successfully send to the Collector.

I get the following error:
```
Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. IOException: The handshake failed due to an unexpected packet format.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
```

## Additional Context

Add any other context about the problem here. If you followed an existing
documentation, please share the link to it.

**Comment by moinoviimir** [comment]
Seconding this. I have a similar setup and understanding how to resolve this would help my pet project as well.

**Comment by cijothomas** [comment]
Currently OTLP exporter only supports Grpc. Adding support for Http/Json is a feature request. This is not currently in the plan.

**Comment by notcool11** [comment]
@moinoviimir , unfortunately getting OpenShift 3.11 working with gRPC is not possible. The underlying issue is HAProxy because it only supports Http 1.1 calls and gRPC needs 2.0.

You would have to go to at least [OpenShift version 4.5 to get everything OTB](https://www.openshift.com/blog/grpc-or-http/2-ingress-connectivity-in-openshift). I read some articles on people using older versions and manually updating just the HAProxy, didn't want to go that route. (pun intended ;)

Also, in that link it just briefly hints at certificates but that tripped me up pretty bad. We previously had the Jaeger Http route edge terminated but that is not allowed for gRPC, you have to use PassThrough or Re-Encrypt routes. The implication here is you have to update the YAML for the collector to include the certification definition, if you don't then it will not be able to decrypt the calls.

```
        otlp:
          protocols:
            grpc:             
             tls_settings:                
                cert_file: "/etc/certs/cert"
                key_file: "/etc/certs/key"
```

Working fine for us in OpenShift 4.6 now. Good luck!!
