### ISSUE TITLE
OpenTelemetryProtocol exporter does not work for netcoreapp3.1

### ISSUE THREAD

**Issue by epaulsen** [open-telemetry/opentelemetry-dotnet#2448]
# Bug Report

```
<PackageReference Include="OpenTelemetry" Version="1.1.0" />
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.1.0" />

```

## Symptom

OpenTelemetryProtocol exporter does not work for netcoreapp3.1

**What is the expected behavior?**

OpenTelemetry exporter should export spans when targeting netcoreapp3.1

**What is the actual behavior?**

Open telemetry trace log  displays this:

```
Successfully opened file.
2021-10-05T08:32:20.5708253Z:Exporter failed send spans to collector. Data will not be sent. Exception: {0}{Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The response ended prematurely.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Opentelemetry.Proto.Collector.Trace.V1.TraceService.TraceServiceClient.Export(ExportTraceServiceRequest request, CallOptions options)
   at Opentelemetry.Proto.Collector.Trace.V1.TraceService.TraceServiceClient.Export(ExportTraceServiceRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at OpenTelemetry.Exporter.OtlpTraceExporter.Export(Batch`1& activityBatch)}

```

## Reproduce

Full repro can be found in this repository: https://github.com/epaulsen/opentelemetry-issue-repro

You need a running collector.  This can be done using docker, like so:
```
docker run -p 4317:4317 otel/opentelemetry-collector:latest
```

```
git clone https://github.com/epaulsen/opentelemetry-issue-repro
cd opentelemetry-issue-repro
dotnet run
```
After this, the .log file will contain the contents shown in actual behavior.

## Additional Context

Changing the target framework to `net5.0` in the csproj file will make the error go away, and spans are exported.
This also works fine for .net full-framework projects.

**Comment by pellared** [comment]
I think this should solve your issue https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol#special-case-when-using-insecure-channel

**Comment by epaulsen** [comment]
@cijothomas @pellared You are absolutely right, thanks.  When all else fails, RTFM 😉 
Closing issue
