### ISSUE TITLE
Unit test stability Instrumentation.AspNetCore.Tests.IncomingRequestsCollectionsIsAccordingToTheSpecTests

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#3261]
https://github.com/open-telemetry/opentelemetry-dotnet/runs/6341673991?check_suite_focus=true

```text
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {ac735029-a892-49f8-b14e-27dfa0215199} may be persisted to storage in unencrypted form.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: exception description
   at OpenTelemetry.Instrumentation.AspNetCore.Tests.IncomingRequestsCollectionsIsAccordingToTheSpecTests.TestCallbackMiddlewareImpl.ProcessAsync(HttpContext context) in /home/runner/work/opentelemetry-dotnet/opentelemetry-dotnet/test/OpenTelemetry.Instrumentation.AspNetCore.Tests/IncomingRequestsCollectionsIsAccordingToTheSpecTests.cs:line 185
   at TestApp.AspNetCore._3._1.CallbackMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/opentelemetry-dotnet/opentelemetry-dotnet/test/TestApp.AspNetCore.3.1/CallbackMiddleware.cs:line 34
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
warn: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[2]
      The response has already started, the error page middleware will not be executed.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: exception description
   at OpenTelemetry.Instrumentation.AspNetCore.Tests.IncomingRequestsCollectionsIsAccordingToTheSpecTests.TestCallbackMiddlewareImpl.ProcessAsync(HttpContext context) in /home/runner/work/opentelemetry-dotnet/opentelemetry-dotnet/test/OpenTelemetry.Instrumentation.AspNetCore.Tests/IncomingRequestsCollectionsIsAccordingToTheSpecTests.cs:line 185
   at TestApp.AspNetCore._3._1.CallbackMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/opentelemetry-dotnet/opentelemetry-dotnet/test/TestApp.AspNetCore.3.1/CallbackMiddleware.cs:line 34
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
warn: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[2]
      The response has already started, the error page middleware will not be executed.
```

**Comment by reyang** [comment]
Similar failure https://github.com/open-telemetry/opentelemetry-dotnet/runs/6183153070?check_suite_focus=true.

**Comment by reyang** [comment]
Similar failure https://github.com/open-telemetry/opentelemetry-dotnet/runs/6019064982?check_suite_focus=true.
