### ISSUE TITLE
Test stability - PrometheusExporterHttpServerTests.PrometheusExporterHttpServerIntegration

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#3292]
https://github.com/open-telemetry/opentelemetry-dotnet/runs/6511353944?check_suite_focus=true

```text
[xUnit.net 00:00:00.81]     OpenTelemetry.Exporter.Prometheus.Tests.PrometheusExporterHttpServerTests.PrometheusExporterHttpServerIntegration [FAIL]
[xUnit.net 00:00:00.81]       System.Net.Http.HttpRequestException : Connection refused (localhost:4983)
[xUnit.net 00:00:00.81]       ---- System.Net.Sockets.SocketException : Connection refused
[xUnit.net 00:00:00.81]       Stack Trace:
[xUnit.net 00:00:00.82]            at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:00.82]            at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:00.82]            at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:00.82]            at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
[xUnit.net 00:00:00.82]            at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
[xUnit.net 00:00:00.82]            at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:00.82]            at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[xUnit.net 00:00:00.82]            at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:00.82]            at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[xUnit.net 00:00:00.82]         /home/runner/work/opentelemetry-dotnet/opentelemetry-dotnet/test/OpenTelemetry.Exporter.Prometheus.Tests/PrometheusExporterHttpServerTests.cs(159,0): at OpenTelemetry.Exporter.Prometheus.Tests.PrometheusExporterHttpServerTests.RunPrometheusExporterHttpServerIntegrationTest(Boolean skipMetrics)
[xUnit.net 00:00:00.82]         /home/runner/work/opentelemetry-dotnet/opentelemetry-dotnet/test/OpenTelemetry.Exporter.Prometheus.Tests/PrometheusExporterHttpServerTests.cs(36,0): at OpenTelemetry.Exporter.Prometheus.Tests.PrometheusExporterHttpServerTests.PrometheusExporterHttpServerIntegration()
[xUnit.net 00:00:00.82]         --- End of stack trace from previous location ---
[xUnit.net 00:00:00.82]         ----- Inner Stack Trace -----
[xUnit.net 00:00:00.82]            at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[xUnit.net 00:00:00.82]            at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
[xUnit.net 00:00:00.82]            at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
[xUnit.net 00:00:00.82]            at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
  Passed OpenTelemetry.Exporter.Prometheus.Tests.PrometheusExporterMiddlewareTests.PrometheusExporterMiddlewareIntegration_MixedPredicateAndPath [2 ms]
  Failed OpenTelemetry.Exporter.Prometheus.Tests.PrometheusExporterHttpServerTests.PrometheusExporterHttpServerIntegration [51 ms]
  Error Message:
   System.Net.Http.HttpRequestException : Connection refused (localhost:4983)
---- System.Net.Sockets.SocketException : Connection refused
  Stack Trace:
     at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OpenTelemetry.Exporter.Prometheus.Tests.PrometheusExporterHttpServerTests.RunPrometheusExporterHttpServerIntegrationTest(Boolean skipMetrics) in /home/runner/work/opentelemetry-dotnet/opentelemetry-dotnet/test/OpenTelemetry.Exporter.Prometheus.Tests/PrometheusExporterHttpServerTests.cs:line 159
   at OpenTelemetry.Exporter.Prometheus.Tests.PrometheusExporterHttpServerTests.PrometheusExporterHttpServerIntegration() in /home/runner/work/opentelemetry-dotnet/opentelemetry-dotnet/test/OpenTelemetry.Exporter.Prometheus.Tests/PrometheusExporterHttpServerTests.cs:line 36
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
```

**Comment by reyang** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/runs/6580933243?check_suite_focus=true

**Comment by TimothyMothra** [comment]
I saw this one today.
Linux & NetCoreApp3.1
https://github.com/open-telemetry/opentelemetry-dotnet/runs/7505347817?check_suite_focus=true

**Comment by reyang** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/7617302298/job/20746039208?pr=5243

**Comment by reyang** [comment]
@CodeBlanch assigning this to you since it was introduced by https://github.com/open-telemetry/opentelemetry-dotnet/pull/2465/files.
