### ISSUE TITLE
Zipkin,  Jaeger, and OTLP exporters don't work in blazor wasm apps on .NET 6+

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#3577]
# Bug Report

```xml
<PackageReference Include="OpenTelemetry" Version="1.4.0-alpha.1" />
<PackageReference Include="OpenTelemetry.Exporter.Zipkin" Version="1.4.0-alpha.1" />
```

on .NET 6+ in Blazor WASM client app

## Symptom

No telemetry is coming to Jaeger, Zipkin or OTel Collector. No exceptions or errors show up in the console.
Console exporter shows manually created activities in the browser console.

**What is the expected behavior?**

Manually created activities are exported to the destination.

**What is the actual behavior?**

No telemetry is coming to Jaeger, Zipkin, or OTel Collector. 

## Reproduce
[blazor-web.zip](https://github.com/open-telemetry/opentelemetry-dotnet/files/9330551/blazor-web.zip)

## Additional Context

The problem is here:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/d1da1d66a3ab4369144e752b47f80dc1f63ae5b3/src/OpenTelemetry.Exporter.Zipkin/ZipkinExporter.cs#L80-L84

Sync Send throws `PlatformNotSupportedExceptions`

``` log
at System.Net.Http.BrowserHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)\n  
at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n  
at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, CancellationToken cancellationToken)
at OpenTelemetry.Exporter.ZipkinExporter.Export(Batch`1& batch) in C:\\repo\\deleteme\\BlazorApp3\\BlazorApp3\\Client\\ZipkinExporter.cs:line 79
```

Even though, it's.NET6, the right heuristic to check could be [`TARGET_BROWSER`](https://github.com/dotnet/runtime/blob/4cbe6f99d23e04c56a89251d49de1b0f14000427/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L13) but it'd require browser target for OTel exporters...

**Comment by lmolkova** [comment]
And here's the cmd line for Jaeger with CORS config

```docker run -d --name jaeger -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 -e COLLECTOR_OTLP_ENABLED=true  -p 6831:6831/udp   -p 6832:6832/udp   -p 5778:5778   -p 16686:16686   -p 4317:4317   -p 4318:4318  -p 14250:14250   -p 14268:14268   -p 14269:14269   -p 9411:9411 -e JAEGER_REPORTER_LOG_SPANS=true  jaegertracing/all-in-one:1.37 --log-level=debug   --collector.zipkin.allowed-origins="*" --collector.zipkin.allowed-headers="*"```
