### ISSUE TITLE
Zipkin exporter: hit exception System.TypeInitializationException on net462

### ISSUE THREAD

**Issue by muhaook** [open-telemetry/opentelemetry-dotnet#3747]
# Bug Report

- List of all OpenTelemetry NuGet packages:

![otel_libs](https://user-images.githubusercontent.com/52417764/194851119-995a9062-45cb-4c39-b2e7-165cf66d1f8a.png)

- Runtime version:

net462
Windows 10 
IIS 10

## Symptom

Was using zipkin exporter but failed with exception below. This happened on net 462 only; did not see it on net core 3.1 / net 6.0
```
[2022-10-10T10:48:34.4185033Z] [Error] EventSource=OpenTelemetry-Exporter-Zipkin, Message=Failed to export activities: 'System.TypeInitializationException: The type initializer for 'OpenTelemetry.Exporter.Zipkin.Implementation.ZipkinSpanJsonHelper' threw an exception. ---> System.MissingMethodException: Method not found: 'System.Text.Json.JsonEncodedText System.Text.Json.JsonEncodedText.Encode(System.String, System.Text.Encodings.Web.JavaScriptEncoder)'.
   at OpenTelemetry.Exporter.Zipkin.Implementation.ZipkinSpanJsonHelper..cctor()
   --- End of inner exception stack trace ---
   at OpenTelemetry.Exporter.Zipkin.Implementation.ZipkinSpan.Write(Utf8JsonWriter writer)
   at OpenTelemetry.Exporter.ZipkinExporter.JsonContent.SerializeToStreamInternal(Stream stream)
   at OpenTelemetry.Exporter.ZipkinExporter.JsonContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.LoadIntoBufferAsync(Int64 maxBufferSize)
   at System.Net.Http.HttpClientHandler.PrepareAndStartContentUpload(RequestState state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenTelemetry.Exporter.ZipkinExporter.Export(Batch`1& batch)' 
```
env variables on IIS:
```
<add name="OTEL_TRACES_EXPORTER" value="zipkin" />
<add name="OTEL_EXPORTER_ZIPKIN_ENDPOINT" value="https://aaaac.cloud.com/20200101/observations/private-span?dataFormat=zipkin&amp;dataFormatVersion=2&amp;dataKey=2U24" />
```

**What is the expected behavior?**

Data were sent via zipkin exporter successfully. No exception.

**Comment by pellared** [comment]
Are these the NuGet packages added to the instrumented application?

If so I would try adding https://www.nuget.org/packages/System.Text.Json as a workaround.

**Comment by muhaook** [comment]
@pellared , it is auto-instrumention (bytecode instrumentation), nothing was changed in intrumented application

**Comment by pellared** [comment]
Shouldn't we move the issue to https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation?
If you know that it is a bug in this repo then you might have to provide more details.
