### ISSUE TITLE
Make W3C trace-context test suite pass

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#404]
Check out https://github.com/open-telemetry/opentelemetry-dotnet/pull/403

**Comment by lmolkova** [comment]
After #418 we still have a few failures related to traceparent parsing.

Traceparent parsing is baked into .NET [Activity](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs).

Reasons for this failures are in several cases are caused by it's tolerance for invalid parts of traceparent: if one part is wrong, Activity will still use other parts.

This explains following failures:
- `test_traceparent_parent_id_all_zero` 
- `test_traceparent_parent_id_illegal_characters`

E.g.
- `00-XY112233445566778899aabbccddeeff-0123456789abcdef-01`, traceId will be regenerated, parent and flags will remain
- `00-00112233445566778899aabbccddeeff-XY23456789abcdef-01`, parentId will be `default` traceId and flags will remain.

.NET choice is motivated by a bit better perf (it doesn't need to scan through the whole traceparent extra time to check it's valid) and a bit easier implementation and lack of obvious reasons to discard valid parts. .NET implementation also is 1 year old and might implement CR version of spec.
At this point, it's not reasonable to change (this is technically behavior change).

Other failures are addressed via https://github.com/dotnet/runtime/pull/1199
- `test_traceparent_trace_flags_illegal_characters`
- `test_traceparent_version_0xcc`
- `test_traceparent_version_illegal_characters` 

After it's done and shipped, we'll still have failures:
- `0.-00112233445566778899aabbccddeeff-0123456789abcdef-01`, version is not allowed, traceId/parentId/flags will be reused if valid
- `00-00112233445566778899aabbccddeeff-0123456789abcdef-.0`, traceId/parentId will be reused if valid, flags will be set to 00

Since there is no action item on OTel side, I'm closing this issue. Feel free to reopen if needed.

```
STRICT_LEVEL: 2
harness listening on http://127.0.0.1:7777
test_multiple_requests_with_illegal_traceparent (__main__.AdvancedTest) ... ok
test_multiple_requests_with_valid_traceparent (__main__.AdvancedTest) ... ok
test_multiple_requests_without_traceparent (__main__.AdvancedTest) ... ok
test_both_traceparent_and_tracestate_missing (__main__.TraceContextTest) ... ok
test_traceparent_duplicated (__main__.TraceContextTest) ... ok
test_traceparent_header_name (__main__.TraceContextTest) ... ok
test_traceparent_header_name_valid_casing (__main__.TraceContextTest) ... ok
test_traceparent_included_tracestate_missing (__main__.TraceContextTest) ... ok
test_traceparent_ows_handling (__main__.TraceContextTest) ... ok
test_traceparent_parent_id_all_zero (__main__.TraceContextTest) ... FAIL
test_traceparent_parent_id_illegal_characters (__main__.TraceContextTest) ... FAIL
test_traceparent_parent_id_too_long (__main__.TraceContextTest) ... ok
test_traceparent_parent_id_too_short (__main__.TraceContextTest) ... ok
test_traceparent_trace_flags_illegal_characters (__main__.TraceContextTest) ... FAIL
test_traceparent_trace_flags_too_long (__main__.TraceContextTest) ... ok
test_traceparent_trace_flags_too_short (__main__.TraceContextTest) ... ok
test_traceparent_trace_id_all_zero (__main__.TraceContextTest) ... ok
test_traceparent_trace_id_illegal_characters (__main__.TraceContextTest) ... ok
test_traceparent_trace_id_too_long (__main__.TraceContextTest) ... ok
test_traceparent_trace_id_too_short (__main__.TraceContextTest) ... ok
test_traceparent_version_0x00 (__main__.TraceContextTest) ... ok
test_traceparent_version_0xcc (__main__.TraceContextTest) ... FAIL
test_traceparent_version_0xff (__main__.TraceContextTest) ... ok
test_traceparent_version_illegal_characters (__main__.TraceContextTest) ... FAIL
test_traceparent_version_too_long (__main__.TraceContextTest) ... ok
test_traceparent_version_too_short (__main__.TraceContextTest) ... ok
test_tracestate_all_allowed_characters (__main__.TraceContextTest) ... ok
test_tracestate_duplicated_keys (__main__.TraceContextTest) ... ok
test_tracestate_empty_header (__main__.TraceContextTest) ... ok
test_tracestate_header_name (__main__.TraceContextTest) ... ok
test_tracestate_header_name_valid_casing (__main__.TraceContextTest) ... ok
test_tracestate_included_traceparent_included (__main__.TraceContextTest) ... ok
test_tracestate_included_traceparent_missing (__main__.TraceContextTest) ... ok
test_tracestate_key_illegal_characters (__main__.TraceContextTest) ... ok
test_tracestate_key_illegal_vendor_format (__main__.TraceContextTest) ... ok
test_tracestate_key_length_limit (__main__.TraceContextTest) ... ok
test_tracestate_member_count_limit (__main__.TraceContextTest) ... ok
test_tracestate_multiple_headers_different_keys (__main__.TraceContextTest) ... ok
test_tracestate_ows_handling (__main__.TraceContextTest) ... ok
test_tracestate_value_illegal_characters (__main__.TraceContextTest) ... ok

======================================================================
FAIL: test_traceparent_parent_id_all_zero (__main__.TraceContextTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 321, in test_traceparent_parent_id_all_zero
    self.assertNotEqual(traceparent.trace_id.hex(), '12345678901234567890123456789012')
AssertionError: '12345678901234567890123456789012' == '12345678901234567890123456789012'

======================================================================
FAIL: test_traceparent_parent_id_illegal_characters (__main__.TraceContextTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 331, in test_traceparent_parent_id_illegal_characters
    self.assertNotEqual(traceparent.trace_id.hex(), '12345678901234567890123456789012')
AssertionError: '12345678901234567890123456789012' == '12345678901234567890123456789012'

======================================================================
FAIL: test_traceparent_trace_flags_illegal_characters (__main__.TraceContextTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 364, in test_traceparent_trace_flags_illegal_characters
    ['traceparent', '00-12345678901234567890123456789012-1234567890123456-.0'],
  File "test.py", line 112, in make_single_request_and_get_tracecontext
    headers = self.make_request(headers)[0]['headers']
  File "test.py", line 92, in make_request
    self.assertTrue(str(idx) in response, 'your test service failed to make a callback to the test harness {}'.format(verbose))
AssertionError: False is not true : your test service failed to make a callback to the test harness

Harness trying to send the following request to your service http://localhost:58325/api/forward

POST http://localhost:58325/api/forward HTTP/1.1
traceparent: 00-12345678901234567890123456789012-1234567890123456-.0

[{'arguments': [],
  'url': 'http://127.0.0.1:7777/555e79aef0ad4226b5d109f1a6370b06.0'}]

Your service http://localhost:58325/api/forward responded with HTTP status 500

Transfer-Encoding: chunked
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Date: Fri, 27 Dec 2019 00:55:41 GMT




======================================================================
FAIL: test_traceparent_version_0xcc (__main__.TraceContextTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 204, in test_traceparent_version_0xcc
    self.assertEqual(traceparent.trace_id.hex(), '12345678901234567890123456789012')
AssertionError: 'd3658c72674f7b48a584c31e899e8ab0' != '12345678901234567890123456789012'
- d3658c72674f7b48a584c31e899e8ab0
+ 12345678901234567890123456789012


======================================================================
FAIL: test_traceparent_version_illegal_characters (__main__.TraceContextTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 239, in test_traceparent_version_illegal_characters
    self.assertNotEqual(traceparent.trace_id.hex(), '12345678901234567890123456789012')
AssertionError: '12345678901234567890123456789012' == '12345678901234567890123456789012'

----------------------------------------------------------------------
Ran 40 tests in 1.209s

FAILED (failures=5)
```
