### ISSUE TITLE
Flaky test ExportMoreSpansThanTheMaxBatchSize 

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#451]
https://dev.azure.com/opentelemetry/pipelines/_build/results?buildId=1133&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=006e6f7c-8314-5e02-a3df-483f3a1f4cfa

[xUnit.net 00:00:04.01]     OpenTelemetry.Trace.Export.Test.BatchingSpanProcessorTest.ExportMoreSpansThanTheMaxBatchSize [FAIL]
  X OpenTelemetry.Trace.Export.Test.BatchingSpanProcessorTest.ExportMoreSpansThanTheMaxBatchSize [1s 25ms]
  Error Message:
   Expected at least 6, got 6
Expected: True
Actual:   False
  Stack Trace:
     at OpenTelemetry.Trace.Export.Test.BatchingSpanProcessorTest.WaitForSpans(TestExporter exporter, Int32 spanCount, TimeSpan timeout) in d:\a\1\s\test\OpenTelemetry.Tests\Impl\Trace\Export\BatchingSpanProcessorTests.cs:line 355
   at OpenTelemetry.Trace.Export.Test.BatchingSpanProcessorTest.ExportMoreSpansThanTheMaxBatchSize() in d:\a\1\s\test\OpenTelemetry.Tests\Impl\Trace\Export\BatchingSpanProcessorTests.cs:line 195

**Comment by lmolkova** [comment]
fixed in #452
