### ISSUE TITLE
.NET 7 - OpenTelemetry.SuppressInstrumentationScope cannot be initialized with PublishTrimmed=true

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet#4600]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

```xml
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.5.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.5.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.5.0-beta.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.GrpcNetClient" Version="1.5.0-beta.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.5.0-beta.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.StackExchangeRedis" Version="1.0.0-rc9.10" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.5.0" />
    <PackageReference Include="OpenTelemetry.ResourceDetectors.Container" Version="1.0.0-beta.4" />
```

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

.NET 7 (works fine for .NET 6) - tested with Windows and Alpine runtime

## Symptom

OpenTelemetry cannot be initialized when published with `PublishTrimmed=True and -p:TrimMode=Link`

**What is the expected behavior?**

No Exception. OTel is working.

**What is the actual behavior?**

Exception while initializing OTel

```log
2023-06-16 07:28:12 Unhandled exception. System.TypeInitializationException: The type initializer for 'OpenTelemetry.SuppressInstrumentationScope' threw an exception.
2023-06-16 07:28:12  ---> System.NullReferenceException: Object reference not set to an instance of an object.
2023-06-16 07:28:12    at OpenTelemetry.Context.RuntimeContext.RegisterSlot[T](String)
2023-06-16 07:28:12    at OpenTelemetry.SuppressInstrumentationScope..cctor()
2023-06-16 07:28:12    --- End of inner exception stack trace ---
2023-06-16 07:28:12    at OpenTelemetry.SuppressInstrumentationScope.get_IsSuppressed()
2023-06-16 07:28:12    at OpenTelemetry.Sdk.get_SuppressInstrumentation()
2023-06-16 07:28:12    at Microsoft.Extensions.DependencyInjection.ProviderBuilderServiceCollectionExtensions.AddOpenTelemetrySharedProviderBuilderServices(IServiceCollection)
2023-06-16 07:28:12    at OpenTelemetry.OpenTelemetryBuilder..ctor(IServiceCollection)
2023-06-16 07:28:12    at Microsoft.Extensions.DependencyInjection.OpenTelemetryServicesExtensions.AddOpenTelemetry(IServiceCollection)
2023-06-16 07:28:12    at Program.<Main>$(String[]) in /usr/src/app/src/Program.cs:line 42
2023-06-16 07:28:12    at Program.<Main>(String[])
```

## Reproduce

Reproducible using opentelemetry-demo:

1. Download OpenTelemetry demo with changes from this commit https://github.com/open-telemetry/opentelemetry-demo/pull/942/commits/23ae56ad582dc643099b9660a0a94cf61053f1aa
2. Execute `docker compose build cartservice` and `docker compose up`.
3. Check logs for cartservice docker.

or
go to 
src\cartservice
and execute
```sh
dotnet restore ./src/cartservice.csproj -r win-x64
dotnet publish ./src/cartservice.csproj -p:PublishSingleFile=true -r win-x64 --self-contained true -p:PublishTrimmed=True -p:TrimMode=Link -c Release -o /cartservice --no-restore
```
Then execute created application

## Additional Context

It is working fine for .NET 6.

Temporary workaround for otel-demo https://github.com/open-telemetry/opentelemetry-demo/pull/942/commits/d24e7ced5c743be98415986b1be8c14d196e2906

**Comment by vitek-karas** [comment]
Do you get any trim warnings when publishing the app?
OpenTelemetry has not been made trim compatible yet, so I would expect there to be warnings which point out that the app may not work.

https://github.com/open-telemetry/opentelemetry-dotnet/issues/3429 tracks the work to make OpenTelemetry AOT compatible which will also make it trim compatible.

**Comment by Kielek** [comment]
@vitek-karas, thanks for explanations. IMO, the strange behavior is that the same operation is working fine for .NET 6, but not for .NET 7.

List of warnings.

```log
(Publish target) (1) ->
       (_RunILLink target) ->
         NugeCachePath\.nuget\packages\opentelemetry.api\1.5.0\lib\netstandard2.0\OpenTelemetry.Api.dll : warning IL2104: Assembly 'OpenTelemetry.Api' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries [C:\GitHub\opentelemetry
       -demo\src\cartservice\src\cartservice.csproj]
         NugeCachePath\.nuget\packages\opentelemetry.instrumentation.aspnetcore\1.5.0-beta.1\lib\net7.0\OpenTelemetry.Instrumentation.AspNetCore.dll : warning IL2104: Assembly 'OpenTelemetry.Instrumentation.AspNetCore' produced trim warnings. For more information
        see https://aka.ms/dotnet-illink/libraries [C:\GitHub\opentelemetry-demo\src\cartservice\src\cartservice.csproj]
         NugeCachePath\.nuget\packages\opentelemetry.instrumentation.grpcnetclient\1.5.0-beta.1\lib\netstandard2.1\OpenTelemetry.Instrumentation.GrpcNetClient.dll : warning IL2104: Assembly 'OpenTelemetry.Instrumentation.GrpcNetClient' produced trim warnings. For
        more information see https://aka.ms/dotnet-illink/libraries [C:\GitHub\opentelemetry-demo\src\cartservice\src\cartservice.csproj]
         NugeCachePath\.nuget\packages\opentelemetry.instrumentation.http\1.5.0-beta.1\lib\netstandard2.0\OpenTelemetry.Instrumentation.Http.dll : warning IL2104: Assembly 'OpenTelemetry.Instrumentation.Http' produced trim warnings. For more information see https
       ://aka.ms/dotnet-illink/libraries [C:\GitHub\opentelemetry-demo\src\cartservice\src\cartservice.csproj]
         NugeCachePath\.nuget\packages\opentelemetry.instrumentation.stackexchangeredis\1.0.0-rc9.10\lib\netstandard2.0\OpenTelemetry.Instrumentation.StackExchangeRedis.dll : warning IL2104: Assembly 'OpenTelemetry.Instrumentation.StackExchangeRedis' produced tri
       m warnings. For more information see https://aka.ms/dotnet-illink/libraries [C:\GitHub\opentelemetry-demo\src\cartservice\src\cartservice.csproj]
         NugeCachePath\.nuget\packages\pipelines.sockets.unofficial\2.2.2\lib\net5.0\Pipelines.Sockets.Unofficial.dll : warning IL2104: Assembly 'Pipelines.Sockets.Unofficial' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries
        [C:\GitHub\opentelemetry-demo\src\cartservice\src\cartservice.csproj]
```

Please close if you think that it will be handled by #3429.

**Comment by vitek-karas** [comment]
The tooling only makes one promise: If there are no warnings, the app should work the same when trimmed as well.
There's no guarantee of the trimmed app's behavior if there's even one warning reported by the tools. It may or may not work. And additionally, the behavior may change release to release. Which seems to be the case here - we're evolving the trimmer and apparently there's been some change in it which made your case not work. But it's very likely that this is caused by some code which produces a warning, so the trimmer is allowed to make such changes.

**Comment by Kielek** [comment]
Thanks for explanation. Closing.
