### ISSUE TITLE
Running into System.MethodAccessException

### ISSUE THREAD

**Issue by swatiMunjal** [open-telemetry/opentelemetry-dotnet#4694]
### Discussed in https://github.com/open-telemetry/opentelemetry-dotnet/discussions/4693

<div type='discussions-op-text'>

<sup>Originally posted by **swatiMunjal** July 25, 2023</sup>
I am using this file as an example to be able to emit metrics and logs via the otel endpoit exporter. (https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/AspNetCore/Program.cs#L156).
I updated all my nuget packages to be able to send logs to an endpoint and that works now - however this call (which was working before the nuget updates) fails now : 

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/29583696/7421170b-3200-4054-919e-e3ec8afc7c09)

Here is the error I am getting: 

Unhandled exception. System.MethodAccessException: Attempt by method 'Microsoft.Extensions.DependencyInjection.OpenTelemetryServicesExtensions.AddOpenTelemetry(Microsoft.Extensions.DependencyInjection.IServiceCollection)' to access method 'OpenTelemetry.Internal.Guard.ThrowIfNull(System.Object, System.String)' failed.
   at Microsoft.Extensions.DependencyInjection.OpenTelemetryServicesExtensions.AddOpenTelemetry(IServiceCollection services)

Any pointers or suggestions? This only started happening when I updated my nuget packages - 
  
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/29583696/164ee679-1459-417a-9b9d-2f5f32ddb026)

</div>

**Comment by swatiMunjal** [comment]
I was able to fix this by upgrading to the latest pre-release

**Comment by iamsourabh-in** [comment]
I have update all the version tt othe latest one, still getting the issue: 

Shockingly, This work fine on my local , but when trying to run in docker (linux base contaiener). It gives the below Error.


`
Unhandled exception. System.MethodAccessException: Attempt by method 'Microsoft.Extensions.DependencyInjection.OpenTelemetryServicesExtensions.AddOpenTelemetry(Microsoft.Extensions.DependencyInjection.IServiceCollection)' to access method 'OpenTelemetry.Internal.Guard.ThrowIfNull(System.Object, System.String)' failed.
   at Microsoft.Extensions.DependencyInjection.OpenTelemetryServicesExtensions.AddOpenTelemetry(IServiceCollection services)
   at Program.<Main>$(String[] args) in /src/dot3/Program.cs:line 36
`


Packages i have been using.

```
		<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.7.0-alpha.1" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.7.0-alpha.1" />
		<PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.7.0-alpha.1" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.7.0-alpha.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.5.1-beta.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.5.1-beta.1" />
		<PackageReference Include="OpenTelemetry.Exporter.Zipkin" Version="1.7.0-alpha.1" />
                <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.5.1" />
```


way i am using it is below:


```

// Configure OpenTelemetry tracing & metrics with auto-start using the
// AddOpenTelemetry extension from OpenTelemetry.Extensions.Hosting.
builder.Services.AddOpenTelemetry()
        .WithTracing(otbuilder =>
        {

            // Tracing

            // Ensure the TracerProvider subscribes to any custom ActivitySources.
            otbuilder
                .AddSource(Instrumentation.ActivitySourceName)
                .SetSampler(new AlwaysOnSampler())
                .AddHttpClientInstrumentation()
                .AddAspNetCoreInstrumentation();


            // Use IConfiguration binding for AspNetCore instrumentation options.
            builder.Services.Configure<AspNetCoreInstrumentationOptions>(builder.Configuration.GetSection("AspNetCoreInstrumentation"));

            switch (tracingExporter)
            {

                case "zipkin":
                    otbuilder.AddZipkinExporter();

                    otbuilder.ConfigureServices(services =>
                    {
                        // Use IConfiguration binding for Zipkin exporter options.
                        services.Configure<ZipkinExporterOptions>(builder.Configuration.GetSection("Zipkin"));
                    });
                    break;

                case "otlp":
                    otbuilder.AddOtlpExporter(otlpOptions =>
                    {
                        // Use IConfiguration directly for Otlp exporter endpoint option.
                        otlpOptions.Endpoint = new Uri(builder.Configuration.GetValue<string>("Otlp:Endpoint"));
                    });
                    break;

                default:
                    otbuilder.AddConsoleExporter();
                    break;
            }

        })
        .WithMetrics(otbuilder =>
        {
            // Metrics
            var resource = ResourceBuilder.CreateDefault().AddService("Uploader.Api", "Uploader");

            // Ensure the MeterProvider subscribes to any custom Meters.
            otbuilder
                .AddMeter(Instrumentation.MeterName)
                .SetResourceBuilder(resource)
                .AddRuntimeInstrumentation()
                .AddHttpClientInstrumentation()
                .AddAspNetCoreInstrumentation();

            switch (metricsExporter)
            {
                case "prometheus":
                    otbuilder.AddPrometheusExporter(options =>
                    {
                        options.ScrapeEndpointPath = "metrics";
                        // Use your endpoint and port here
                        //options.HttpListenerPrefixes = new string[] { $"http://localhost:{9090}/" };
                        options.ScrapeResponseCacheDurationMilliseconds = 0;
                    }
                    );
                    break;
                case "otlp":
                    otbuilder.AddOtlpExporter(otlpOptions =>
                    {
                        // Use IConfiguration directly for Otlp exporter endpoint option.
                        otlpOptions.Endpoint = new Uri(builder.Configuration.GetValue<string>("Otlp:Endpoint"));
                    });
                    break;
                default:
                    otbuilder.AddConsoleExporter();
                    break;
            }
        });



```
