### ISSUE TITLE
Flaky AspNetCore instrumentation unit tests

### ISSUE THREAD

**Issue by utpilla** [open-telemetry/opentelemetry-dotnet#4763]
CI checks for build are failing intermittently because of AspNetCore instrumentation unit tests failing with `System.InvalidOperationException : Unable to build IHost`

These are usually only observed for `IncomingRequestsCollectionsIsAccordingToTheSpecTests`.

Here are few sample PR runs:
- https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/5828125678/job/15805277846?pr=4726
- https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/5828163014/job/15805377657?pr=4753

**Comment by TimothyMothra** [comment]
Tests that failed:
- OpenTelemetry.Instrumentation.AspNetCore.Tests.IncomingRequestsCollectionsIsAccordingToTheSpecTests.SuccessfulTemplateControllerCallGeneratesASpan_Old
- OpenTelemetry.Instrumentation.AspNetCore.Tests.IncomingRequestsCollectionsIsAccordingToTheSpecTests_New.SuccessfulTemplateControllerCallGeneratesASpan_New

Runtime; net6.0

Call stack:
```
Error Message:
   System.InvalidOperationException : Unable to build IHost
  Stack Trace:
     at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass8_0.<ResolveHostFactory>b__0(String[] args)
   at Microsoft.AspNetCore.Mvc.Testing.DeferredHostBuilder.Build()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DelegatedWebApplicationFactory.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
```


These tests are nearly identical except for inspecting different attributes (Old vs New). 
These were split into different classes because they were having concurrency issues when in the same class.


This is the exact same call stack as was reported here: https://github.com/dotnet/runtime/issues/60891
This is described as a timeout issue.
