### ISSUE TITLE
Test stability - OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests.MockCollectorIntegrationTests.TestRecoveryAfterFailedExport

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#4929]
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/17327289/aed61c36-c38d-4653-ae9d-e24260f8121d)

**Comment by reyang** [comment]
Failed again https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/6499900795/job/17654192628?pr=4933

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/17327289/530a3b14-a8fa-46eb-b252-580429b637f8)

**Comment by reyang** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/7834756766/job/21378670233?pr=5329

```text
[xUnit.net 00:00:09.06]     OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests.MockCollectorIntegrationTests.TestRecoveryAfterFailedExport [FAIL]
[xUnit.net 00:00:09.06]       Assert.Equal() Failure: Values differ
[xUnit.net 00:00:09.06]       Expected: Failure
[xUnit.net 00:00:09.06]       Actual:   Success
[xUnit.net 00:00:09.06]       Stack Trace:
[xUnit.net 00:00:09.07]         D:\a\opentelemetry-dotnet\opentelemetry-dotnet\test\OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests\MockCollectorIntegrationTests.cs(84,0): at OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests.MockCollectorIntegrationTests.TestRecoveryAfterFailedExport()
[xUnit.net 00:00:09.07]         --- End of stack trace from previous location ---
  Failed OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests.MockCollectorIntegrationTests.TestRecoveryAfterFailedExport [6 s]
  Error Message:
   Assert.Equal() Failure: Values differ
Expected: Failure
Actual:   Success
  Stack Trace:
     at OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests.MockCollectorIntegrationTests.TestRecoveryAfterFailedExport() in D:\a\opentelemetry-dotnet\opentelemetry-dotnet\test\OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests\MockCollectorIntegrationTests.cs:line 84
--- End of stack trace from previous location ---
```
