### ISSUE TITLE
gRPC loading issue with OTLP Exporter on .NET Framework 4.8

### ISSUE THREAD

**Issue by ClumsyPenguin** [open-telemetry/opentelemetry-dotnet#4999]
# Bug Report

### OTel packages:
OpenTelemetry V1.6.0
OpenTelemetry.Api V1.6.0
OpenTelemetry.Api.ProviderBuilderExtensions V1.6.0
OpenTelemetry.Exporter.Console V1.6.0
OpenTelemetry.Exporter.OpenTelemetryProtocol_V1.6.0_
OpenTelemetry.Extensions.Hosting V1.6.0
OpenTelemetry.Instrumentation.AspNet V1.6.0-beta.1
OpenTelemetry.Instrumentation.AspNet.TelemetryHtppModule V1.6.0-beta.1
OpenTelemetry.Instrumentation.Http V1.5.1-beta.1
OpenTelemetry.Instrumentation.SqlClient V1.5.1-beta.1

### gRPC packages:
Grpc.Core.Api V2.46.6
Grpc V2.46.6
Grpc.Core V2.46.6

Runtime version: net48

### StackTrace of the issue
```
System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Grpc.Core\v4.0_2.0.0.0__d754f35622e28bad\grpc_csharp_ext.x64.dll,C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Grpc.Core\v4.0_2.0.0.0__d754f35622e28bad\runtimes/win-x64/native\grpc_csharp_ext.x64.dll,C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Grpc.Core\v4.0_2.0.0.0__d754f35622e28bad\../..\runtimes/win-x64/native\grpc_csharp_ext.x64.dll
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUsingExplicitLoad()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials)
   at OpenTelemetry.Exporter.OtlpExporterOptionsExtensions.CreateChannel(OtlpExporterOptions options)
   at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.ExportClient.OtlpGrpcTraceExportClient..ctor(OtlpExporterOptions options, TraceServiceClient traceServiceClient)
   at OpenTelemetry.Exporter.OtlpExporterOptionsExtensions.GetTraceExportClient(OtlpExporterOptions options)
   at OpenTelemetry.Exporter.OtlpTraceExporter..ctor(OtlpExporterOptions exporterOptions, SdkLimitOptions sdkLimitOptions, IExportClient`1 exportClient)
   at OpenTelemetry.Trace.OtlpTraceExporterHelperExtensions.BuildOtlpExporterProcessor(OtlpExporterOptions exporterOptions, SdkLimitOptions sdkLimitOptions, IServiceProvider serviceProvider, Func`2 configureExporterInstance)
   at OpenTelemetry.Trace.OtlpTraceExporterHelperExtensions.<>c__DisplayClass2_0.<AddOtlpExporter>b__1(IServiceProvider sp)
   at OpenTelemetry.Trace.TracerProviderBuilderExtensions.<>c__DisplayClass8_0.<AddProcessor>b__0(IServiceProvider sp, TracerProviderBuilder builder)
   at OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracingServiceCollectionExtensions.ConfigureTracerProviderBuilderCallbackWrapper.ConfigureBuilder(IServiceProvider serviceProvider, TracerProviderBuilder tracerProviderBuilder)
   at OpenTelemetry.Trace.TracerProviderSdk..ctor(IServiceProvider serviceProvider, Boolean ownsServiceProvider)
   at OpenTelemetry.Trace.TracerProviderBuilderBase.Build()
   at OpenTelemetry.Trace.TracerProviderBuilderBase.InvokeBuild()
   at OpenTelemetry.Trace.TracerProviderBuilderExtensions.Build(TracerProviderBuilder tracerProviderBuilder)
```

**What is the expected behavior?**

Working OTLP exporter in combination with  .NET Framework 4.8

## Reproduce
MVP reproducing the issue described above:
https://github.com/ClumsyPenguin/OtelExporter

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/22469147/4b087c2d-5f7b-4db5-8706-b920414a37c9)

## Additional context
I am using manual instrumentation through an interceptor in our common interfaces for Services, Repositories, Controllers, etc...

Previously i was using Jaeger exporter to view my traces in Jaeger UI. However since that package is deprecated i am trying to switch to the OTLP exporter at this moment.

Current workaround is to switch back to the deprecated Jaeger exporter for now.

_Ticker originates from https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/3044_

**Comment by ClumsyPenguin** [comment]
### Possible related prs/issues:
https://github.com/open-telemetry/opentelemetry-dotnet/pull/4860
https://github.com/open-telemetry/opentelemetry-dotnet/pull/4719
https://github.com/open-telemetry/opentelemetry-dotnet/issues/3421
https://github.com/open-telemetry/opentelemetry-dotnet/issues/4613

**Comment by tarasevichvlad** [comment]
Hi. Any info for this topic? Any workround?

**Comment by smunukuru170** [comment]
hi..wondering if there is a solution for this. I am having the same issue when implementing zero code instrumentation for a .net component running on docker.

**Comment by philipuren** [comment]
I have the same problem, also with .Net Framework 4.8, but with the same code in .Net 8 I didn't have any problems.
Then I copied
C:\Users\Me\.nuget\packages\grpc.core\2.44.0\runtimes\win-x64\native\grpc_csharp_ext.x64.dll
into
C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Grpc.Core\v4.0_2.0.0.0__d754f35622e28bad
This temporary work-around worked, although I hate it.

**Comment by rajkumar-rangaraj** [comment]
The issue has been resolved in version 1.11.0-rc.1 of `OpenTelemetry.Exporter.OpenTelemetryProtocol`. In this version, we have removed the dependencies on Grpc packages, which should fix the problem.

**Comment by smunukuru170** [comment]
@rajkumar-rangaraj - how do I use that version of the exporter? I am implementing zero code instrumentation using the steps in this url: https://opentelemetry.io/docs/zero-code/net/. There is no reference to the version of the exporter here. Appreciate your guidance

**Comment by Kielek** [comment]
> @rajkumar-rangaraj - how do I use that version of the exporter? I am implementing zero code instrumentation using the steps in this url: https://opentelemetry.io/docs/zero-code/net/. There is no reference to the version of the exporter here. Appreciate your guidance

It is not part of [OTel .NET Auto](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/), yet. There is a plan to make a stable release in the next month. Then it can be included into AutoInstrumentation.
