### ISSUE TITLE
NotSupportedException: Services cannot be configured after ServiceProvider has been created.

### ISSUE THREAD

**Issue by bbwang13** [open-telemetry/opentelemetry-dotnet#5132]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* OpenTelemetry.Exporter.Geneva 1.6.0
* net8.0

## Symptom

I used `AddOpenTelemetry().WithMetrics()` to add metrics and set Geneva exporting options specifying the Geneva account and namespace. Build passed but throw exceptions at runtime.

**What is the expected behavior?**

No exceptions.

What did you expect to see?

No exceptions and metrics can be uploaded to Geneva backend.

What did you see instead?

```
Unhandled exception. System.NotSupportedException: Services cannot be configured after ServiceProvider has been created.
   at OpenTelemetry.Metrics.MeterProviderBuilderSdk.ConfigureServices(Action`1 configure)
   at OpenTelemetry.Metrics.OpenTelemetryDependencyInjectionMeterProviderBuilderExtensions.ConfigureServices(MeterProviderBuilder meterProviderBuilder, Action`1 configure)
   at OpenTelemetry.Exporter.Geneva.GenevaMetricExporterExtensions.AddGenevaMetricExporter(MeterProviderBuilder builder, String name, Action`1 configure)
   at OpenTelemetry.Exporter.Geneva.GenevaMetricExporterExtensions.AddGenevaMetricExporter(MeterProviderBuilder builder, Action`1 configure)
   at Microsoft.R9.Extensions.Metering.Exporters.GenevaMeteringExporterExtensions.AddGenevaExporter(MeterProviderBuilder builder, IEnumerable`1 enrichers, GenevaMeteringExporterOptions options, Action`1 configure)
   at Microsoft.R9.Extensions.Metering.Exporters.GenevaMeteringExporterExtensions.<>c__DisplayClass2_0.<AddGenevaExporter>b__1(IServiceProvider sp, MeterProviderBuilder meterProviderBuilder)
   at OpenTelemetry.Metrics.OpenTelemetryDependencyInjectionMetricsServiceCollectionExtensions.ConfigureMeterProviderBuilderCallbackWrapper.ConfigureBuilder(IServiceProvider serviceProvider, MeterProviderBuilder meterProviderBuilder)
   at OpenTelemetry.Metrics.MeterProviderSdk..ctor(IServiceProvider serviceProvider, Boolean ownsServiceProvider)
   at OpenTelemetry.Metrics.MeterProviderBuilderBase.<>c.<.ctor>b__3_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OpenTelemetry.Extensions.Hosting.Implementation.TelemetryHostedService.Initialize(IServiceProvider serviceProvider)
   at OpenTelemetry.Extensions.Hosting.Implementation.TelemetryHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
```

## Reproduce

The code at the DI part like:
```C#
                    services.AddOpenTelemetry().WithMetrics(builder =>
                    {
                        var config = context.Configuration.GetSection("Metrics");
                        builder.AddMetering()
                            .AddView((instrument) =>
                            {
                                if (instrument.GetType().Name.Contains("Histogram"))
                                {
                                    return new Base2ExponentialBucketHistogramConfiguration();
                                }

                                return null;
                            })
                            .AddGenevaExporter(options =>
                            {
                                options.MonitoringAccount = "A";
                                options.MonitoringNamespace = "B";
                            });
                    });

```

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

## Additional Context

I tried to add `GenevaMetringOptions` outside the `OpenTelemetry` part, no exceptions, but the metrics still cannot upload:

```C#
                    services.Configure<GenevaMeteringOptions>(options =>
                    {
                        options.MonitoringAccount = "A";
                        options.MonitoringNamespace = "B";
                    });
```

**Comment by cijothomas** [comment]
> OpenTelemetry.Exporter.Geneva
> Microsoft.R9.Extensions.Metering.Exporters.GenevaMeteringExporterExtensions

These are components not part of this repo, so we can't really help here. I'd suggest to follow up with the owners of the respective packages.

If you have issues with components shipped from this repo, please share a minimal repro app, and we can help.
