### ISSUE TITLE
Using TracerShim results in ConditionalWeakTable ArgumentException: "An item with the same key has already been added."

### ISSUE THREAD

**Issue by tvandenheuvel** [open-telemetry/opentelemetry-dotnet#5439]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

AspNetCore app
- `Npgsql.OpenTelemetry 8.0.2`
- `OpenTelemetry 1.7.0`
- `OpenTelemetry.Exporter.Console 1.7.0`
- `OpenTelemetry.Extensions.Hosting 1.7.0`
- `OpenTelemetry.Instrumentation.AspNetCore 1.7.1`
- `OpenTelemetry.Instrumentation.Http 1.7.1`
- `OpenTelemetry.Instrumentation.Runtime 1.7.0`
- `OpenTelemetry.Shims.OpenTracing 1.7.0-beta.1`

Library
- `OpenTracing 0.12.1`

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

- net8.0 aspnetcore webapp 
- net6.0 library

## Symptom

When building and starting child spans using the TracerShim injected as OpenTracer ITracer, the ScopeManagerShim throws a ArgumentException

**What is the expected behavior?**

That a span is created and activated

**What is the actual behavior?**

```
System.ArgumentException: An item with the same key has already been added.
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.Add(TKey key, TValue value)
   at OpenTelemetry.Shims.OpenTracing.ScopeManagerShim.Activate(ISpan span, Boolean finishSpanOnDispose)
   at OpenTelemetry.Shims.OpenTracing.SpanBuilderShim.StartActive(Boolean finishSpanOnDispose)
   at SubLibrary.SubClassWithOpenTracing.RecursiveChildSpan(String input, Int32 recursiveDepth) in .\OpenTelemetryTesting\SubLibrary\SubClassWithOpenTracing.cs:line 24
   at SubLibrary.SubClassWithOpenTracing.ParentSpan(String input) in.\OpenTelemetryTesting\SubLibrary\SubClassWithOpenTracing.cs:line 18
   at OpenTelemetryTesting.Program.<>c__DisplayClass0_0.<Main>b__0() in .\OpenTelemetryTesting\OpenTelemetryTesting\Program.cs:line 28
   at lambda_method2(Closure, Object, HttpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

## Reproduce

https://github.com/tvandenheuvel/OpenTelemetryTesting

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by meganaut** [comment]
I am getting the same issue with

`<PackageReference Include="OpenTelemetry" Version="1.9.0"/>
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.9.0"/>
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.9.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.9.0"/>
        <PackageReference Include="OpenTelemetry.Shims.OpenTracing" Version="1.9.0-beta.2"/>`

**Comment by Kielek** [comment]
Guys, could you please provide [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

In this case, I mean small portion of code (whole project) where we can observe problems. It should reduce time to response.

**Comment by lucasoares** [comment]
Same in our applications. We updated from 

```
    <PackageReference Include="OpenTelemetry.Shims.OpenTracing" Version="1.0.0-rc9.9" />
```

to

```
    <PackageReference Include="OpenTelemetry.Shims.OpenTracing" Version="1.9.0-beta.2" />
```

And this issue started to throw errors throughout our codebase.

**Comment by lucasoares** [comment]
I did a little debugging on this, and it looks like the problem is happening in this line:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/a871f0fc687d610bea0a8aa0df9f7f2ca6630615/src/OpenTelemetry.Shims.OpenTracing/ScopeManagerShim.cs#L62

The issue occurs because the same TelemetrySpan is activated more than once.
When Activate is called multiple times for the same span, the code tries to insert it again into the ConditionalWeakTable. Since ConditionalWeakTable.Add does not allow duplicate keys, this results in an ArgumentException.

I haven’t figured out yet why it is being activated multiple times. The Activate code in ScopeManagerShim hasn’t changed between `1.0.0-rc9.9` and `1.9.0-beta.2`, so it seems like something else upstream is triggering the duplicate activations.

**Comment by yehaotian** [comment]
Hi team, can someone help take a look at the issue?

**Comment by martincostello** [comment]
I had a quick look, and the exception is coming from here:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/ef4bb190de1402b6b67c156c1c4e8185cd4c3981/src/OpenTelemetry.Shims.OpenTracing/ScopeManagerShim.cs#L62

Tracing through the code, it seems like the likely cause is when either the activity source has no listeners:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/ef4bb190de1402b6b67c156c1c4e8185cd4c3981/src/OpenTelemetry.Api/Trace/Tracer.cs#L203-L206

or `Activity.StartActivity()` returns `null`:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/ef4bb190de1402b6b67c156c1c4e8185cd4c3981/src/OpenTelemetry.Api/Trace/Tracer.cs#L220-L223

That causes the telemetry span to be the same reference to `TelemetrySpan.NoopInstance`, which then ends up being the duplicated key into the `ConditionalWeakTable<K, V>`, causing the exception to be thrown.

However, I'm not sure what the fix _should_ be.

Possibilities include:

1. Special case `shim.Span` being `TelemetrySpan.NoopInstance`, then maybe returning a no-op scope.
2. Use `AddOrUpdate()` instead of `Add()`, but that might mask other bugs.

**Comment by yehaotian** [comment]
the no-op spans could be introduced for non-sampled case, which means the Shim would just break for any instrumentation with no-op optimization

**Comment by Kielek** [comment]
Package marked as deprecated. Closing. https://github.com/open-telemetry/opentelemetry-dotnet/pull/6976
