### ISSUE TITLE
Test stability - OpenTelemetry.Trace.Tests.BatchExportActivityProcessorTest.CheckShutdownExport

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#5525]
https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/8620692586/job/23628054054#step:6:6689

```text
[xUnit.net 00:00:15.67]     OpenTelemetry.Trace.Tests.BatchExportActivityProcessorTest.CheckShutdownExport(timeout: 1) [FAIL]
[xUnit.net 00:00:15.67]       Assert.Single() Failure: The collection was empty
[xUnit.net 00:00:15.68]       Stack Trace:
[xUnit.net 00:00:15.69]         /home/runner/work/opentelemetry-dotnet/opentelemetry-dotnet/test/OpenTelemetry.Tests/Trace/BatchExportActivityProcessorTest.cs(145,0): at OpenTelemetry.Trace.Tests.BatchExportActivityProcessorTest.CheckShutdownExport(Int32 timeout)
```

**Comment by reyang** [comment]
It failed again https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/8807869536/job/24175888451

```text
  Failed OpenTelemetry.Trace.Tests.BatchExportActivityProcessorTest.CheckShutdownExport(timeout: 1) [29 ms]
  Error Message:
   System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
  Stack Trace:
     at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at OpenTelemetry.Trace.Tests.BatchExportActivityProcessorTest.CheckShutdownExport(Int32 timeout) in /home/runner/work/opentelemetry-dotnet/opentelemetry-dotnet/test/OpenTelemetry.Tests/Trace/BatchExportActivityProcessorTest.cs:line 145
```

**Comment by reyang** [comment]
Also here https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/8729663667/job/23952065749.

**Comment by cambeattydev** [comment]
I believe this issue was fixed with #6329. If you don't think so, I try as I'm looking for a good first issue

**Comment by Kielek** [comment]
@cambeattydev, you are probably right. Thanks for spotting this. Closing.

This one #5557 looks like good first issue. Please check comments and previous PR also.
