### ISSUE TITLE
Test Stability - OpenTelemetry.Instrumentation.AspNetCore.Tests.BasicTests.AddAspNetCoreInstrumentation_BadArgs

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#5568]
https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/8666621517/job/23767835550

```text
Failed OpenTelemetry.Instrumentation.AspNetCore.Tests.BasicTests.AddAspNetCoreInstrumentation_BadArgs [1 ms]
  Error Message:
   [Test Class Cleanup Failure (OpenTelemetry.Instrumentation.AspNetCore.Tests.BasicTests)]: System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at System.IO.FileSystemWatcher.StopRaisingEvents()
   at System.IO.FileSystemWatcher.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.Dispose(Boolean disposing)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Dispose(Boolean disposing)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Dispose()
   at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>g__DisposeAsync|16_0(Object o)
   at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
   at Microsoft.Extensions.Hosting.Internal.Host.Dispose()
   at Microsoft.AspNetCore.Mvc.Testing.DeferredHostBuilder.DeferredHost.Dispose()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DisposeAsync()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DisposeAsync()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose(Boolean disposing)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose()
```

**Comment by reyang** [comment]
The instrumentation test issues can migrate to the contrib repo as part of #5526.

**Comment by vishweshbankwar** [comment]
@reyang - This is tracked with https://github.com/open-telemetry/opentelemetry-dotnet/issues/5533. I think we should close this one as the failures are not just confined to `OpenTelemetry.Instrumentation.AspNetCore.Tests.BasicTests.AddAspNetCoreInstrumentation_BadArgs`
