### ISSUE TITLE
ArraySegment ArgumentException in PrometheusCollectionManager on results write

### ISSUE THREAD

**Issue by artem-voropaev** [open-telemetry/opentelemetry-dotnet#5709]
### Package

OpenTelemetry.Exporter.Prometheus.AspNetCore

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry                         | 1.9.0   |
| OpenTelemetry.Exporter.Prometheus.AspNetCore| 1.9.0-beta.1|
| OpenTelemetry.Extensions.Hosting| 1.9.0|
| OpenTelemetry.Instrumentation.AspNetCore| 1.8.1|
| OpenTelemetry.Instrumentation.Http| 1.8.1|
| OpenTelemetry.Instrumentation.Process| 0.5.0-beta.5|
| OpenTelemetry.Instrumentation.Runtime| 1.8.1|

### Runtime Version

net6.0

### Description

On collect metrics exception thrown in PrometheusCollectionManager
CallStack:
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.ArraySegment`1..ctor(T[] array, Int32 offset, Int32 count)
   at OpenTelemetry.Exporter.Prometheus.PrometheusCollectionManager.OnCollect(Batch`1 metrics)

Screenshot:
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/7920253/5e4ecde4-a4a6-43f2-98ee-d426ca5397b4)

### Steps to Reproduce

See Desc.

### Expected Result

Metrics returned

### Actual Result

After some time, metrics not returned.

**Comment by vishweshbankwar** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/5676 should fix this.

**Comment by vishweshbankwar** [comment]
https://www.nuget.org/packages/OpenTelemetry.Exporter.Prometheus.AspNetCore/1.9.0-beta.2 has the fix
