### ISSUE TITLE
Metrics stop exporting at seemingly random times every week or so

### ISSUE THREAD

**Issue by ladenedge** [open-telemetry/opentelemetry-dotnet#5729]
### What is the question?

We're using metrics extensively in our .NET 8 application which is deployed to a dozen or so servers.  Once in a while -- say, once a week -- a single server will stop exporting to our OTel Collector.  The other servers continue to work fine, and restarting our application fixes the problem.

- What might be going wrong here?
- Are there any configuration options that might help?
- How can I debug/diagnose this problem?

Thank you for any help!

### Additional context

Application is .NET 8 with the following OTel packages:

```xml
<PackageReference Include="OpenTelemetry.Contrib.Instrumentation.AWS" Version="1.0.2" />
<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.8.1" />
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.8.1" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.8.1" />
<PackageReference Include="OpenTelemetry.Instrumentation.EventCounters" Version="1.5.1-alpha.1" />
<PackageReference Include="OpenTelemetry.Instrumentation.GrpcNetClient" Version="1.6.0-beta.2" />
<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.8.1" />
```

**Comment by cijothomas** [comment]
Please see if you can get internal logs (Warning and above) https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/README.md#self-diagnostics

Are you missing all metrics from the server, or just a subset of metrics? (There is metric cardinality caps implemented which can explain the behavior, but if it is every metric stopping at the same time, unlikely to be cause).
Is metrics missing in Console too?

**Comment by ladenedge** [comment]
Okay, we found a newly failing server and the diagnostic log helped a great deal.  It appears we are timing out:

> Exporter failed send data to collector to {0} endpoint. Data will not be sent. Exception: {1}{https://myendpoint.com:4317/}{Grpc.Core.RpcException: Status(StatusCode="DeadlineExceeded", Detail="")

Here's the full entry, repeated every minute:

```
2024-07-04T12:43:18.7570236Z:Exporter failed send data to collector to {0} endpoint. Data will not be sent. Exception: {1}{https://myendpoint.com:4317/}{Grpc.Core.RpcException: Status(StatusCode="DeadlineExceeded", Detail="")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at OpenTelemetry.Proto.Collector.Metrics.V1.MetricsService.MetricsServiceClient.Export(ExportMetricsServiceRequest request, CallOptions options)
   at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.ExportClient.OtlpGrpcMetricsExportClient.SendExportRequest(ExportMetricsServiceRequest request, DateTime deadlineUtc, CancellationToken cancellationToken)}
```

So now I have two questions:

1. Is there some way to modify the timeout on the internal OTel gRPC calls?
2. Why might this be happening after a week or so?  Once we do timeout, is this likely to get worse due to the queuing of new metrics?  (Ie. is there any chance of recovering from this condition?)

Thank you again for your help!

**Comment by cijothomas** [comment]
> Is there some way to modify the timeout on the internal OTel gRPC calls?

For gRPC, not much option to customize. There are open issues/prs for related settings that will allow exposing this. Eg: https://github.com/open-telemetry/opentelemetry-dotnet/issues/2009


> Why might this be happening after a week or so? Once we do timeout, is this likely to get worse due to the queuing of new metrics? (Ie. is there any chance of recovering from this condition?)

I don't think any "queue" up occurs today. If a batch is lost due to grpc timeout, its not saved for retry later, instead the next batch is tried. 
(@vishweshbankwar to keep me honest here.)

**Comment by vishweshbankwar** [comment]
> Is there some way to modify the timeout on the internal OTel gRPC calls?

You can increase the timeout period by setting [TimeOutMilliSeconds](https://github.com/open-telemetry/opentelemetry-dotnet/blob/46265e3379ed71ef01666af3e13e6f3803510d61/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs#L108)

> If a batch is lost due to grpc timeout, its not saved for retry later, instead the next batch is tried.

This is correct, even if the [retries](https://github.com/open-telemetry/opentelemetry-dotnet/tree/46265e3379ed71ef01666af3e13e6f3803510d61/src/OpenTelemetry.Exporter.OpenTelemetryProtocol#:~:text=OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY,in%201.8.0.) are enabled. https://github.com/open-telemetry/opentelemetry-dotnet/issues/5436

**Comment by cijothomas** [comment]
> Is there some way to modify the timeout on the internal OTel gRPC calls?
> 
> You can increase the timeout period by setting [TimeoutMilliseconds](https://github.com/open-telemetry/opentelemetry-dotnet/blob/46265e3379ed71ef01666af3e13e6f3803510d61/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs#L108)

Thanks! Even if OTel's export timeout is increased, will it get applied to the timeout used by the GrpcClient itself?

**Comment by cijothomas** [comment]
Thanks!. Looks like https://github.com/open-telemetry/opentelemetry-dotnet/issues/1735 is still open which state we don't really enforce the timeouts, but I could be wrong. (or its only for traces!)

**Comment by ladenedge** [comment]
> You can increase the timeout period by setting [TimeoutMilliseconds](https://github.com/open-telemetry/opentelemetry-dotnet/blob/46265e3379ed71ef01666af3e13e6f3803510d61/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs#L108)

Great info!  However, it looks like the default is 10s, so it worries me that we're exceeding that -- especially if each call only includes the latest metrics.  I could increase it to 20s or 30s, but I wonder if I'm just doing something wrong.  Do you have any suggestions for diagnosing _why_ my sends are exceeding 10s, or just how much data I'm sending?  Or is this more likely a network issue between the servers and the collector?

Thanks again, and feel free to close this issue if you feel you've provided all the info you can!

**Comment by cijothomas** [comment]
> especially if each call only includes the latest metrics.

This is only true if using Delta. If using Cumulative, then everything from start will always be exported... Are you using Delta or Cumulative? 
Also, are there many Observable instruments with callbacks potentially taking a lot of time?

**Comment by ladenedge** [comment]
We are indeed using Delta mode:

```csharp
reader.TemporalityPreference = MetricReaderTemporalityPreference.Delta;
```

We have a handful of observables.  You're suggesting that the time it takes to observe those metrics must be accounted for in the gRPC deadline?  That's interesting.  We've tried to make those calls quick, but it's certainly something we could take a closer look at -- that could also explain why our servers never recover from this condition.

Any other ideas are most welcome, and thank you again for all the help!

**Comment by vishweshbankwar** [comment]
@ladenedge - Just to confirm, you don't have [retries](https://github.com/open-telemetry/opentelemetry-dotnet/tree/46265e3379ed71ef01666af3e13e6f3803510d61/src/OpenTelemetry.Exporter.OpenTelemetryProtocol#:~:text=OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY,in%201.8.0.) enabled, correct?

it's odd that once the server hits DeadlineExceeded, it is not able to recover from that and continues to throw that error until re-started.

**Comment by ladenedge** [comment]
Also, to follow up on the observables: are observables actually queried during the exporter's network call?  Looking over our handful of observable counters, they appear quick (eg. `Dictionary.Count`) -- but is it even possible that they contribute to the missed deadline?

**Comment by cijothomas** [comment]
> are observables actually queried during the exporter's network call?

No. (If you were using Prometheus scraping, then the observables callbacks are done in response to scrape request, so they do contribute to response time of the scrape itself.) In short - observable callback is not at play in your case, as you are doing push exporter. (Sorry I confused you with the mention of observables :( )

**Comment by g3david405** [comment]
I face same issue

**Comment by ladenedge** [comment]
I'd like to try and resurrect this issue because we continue to face this problem.

To recap, we have a pool of 15 servers that live in three datacenters and AWS.  Regardless of the location, they will sometimes stop writing metrics, and they are unable to recover.  Restarting our app (a Windows service) resolves the problem -- for a while.

OTEL diagnostics show a **DeadlineExceeded** error, repeated as nauseum:

```
2024-11-22T14:37:16.7591358Z:Exporter failed send data to collector to {0} endpoint. Data will not be sent. Exception: {1}{https://myendpoint.com:4317/}{Grpc.Core.RpcException: Status(StatusCode="DeadlineExceeded", Detail="")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at OpenTelemetry.Proto.Collector.Metrics.V1.MetricsService.MetricsServiceClient.Export(ExportMetricsServiceRequest request, CallOptions options)
   at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.ExportClient.OtlpGrpcMetricsExportClient.SendExportRequest(ExportMetricsServiceRequest request, DateTime deadlineUtc, CancellationToken cancellationToken)}
```

This occurs seemingly at random, and not necessarily at high-traffic periods.  Here, for example, is a recent look at a metric that stopped writing during a fairly low-traffic period:

![image](https://github.com/user-attachments/assets/c1c397e5-520a-4e4a-8741-b21d2fe9081a)

And here is a shot of another server from the same datacenter over the same period:

![image](https://github.com/user-attachments/assets/d2181c63-6970-4560-a195-a7629652de29)

Also of interest: whatever is happening does not impact traces or logs.  Here is a shot of the faulty server's _traces_ over the same period:

![image](https://github.com/user-attachments/assets/bab9749b-b226-47f9-bc1f-bdd080638caf)

Likewise, logs come in without issue over the same period, though we are using Serilog's OTEL Sink, so it's fairly separate.

Since last I checked it, we have raised our timeout to 30s:

```csharp
exporterOptions.TimeoutMilliseconds = 30000;
```

This timeout change does not seem to have made any difference.

Some conclusions:

- We are writing to an OTEL Collector in AWS, but resetting the Collector does not resolve the problem. (Only resetting the Windows service seems to resolve it.)
- It does not appear to be related to traffic or load, since the fault sometimes occurs at low traffic/load.
- It does not appear to be related to our network, since other servers on the same network continue to work fine.  Moreover, traces and logs from the faulty server _also_ continue to work fine.

Does anyone have any other suggestions for debugging or working around this issue?

**Comment by lfossati-coreview** [comment]
Does anyone have any news about this issue? We are still facing this issue

**Comment by rajkumar-rangaraj** [comment]
> Does anyone have any news about this issue? We are still facing this issue

Does it happen with latest version of OpenTelemetry SDK?

**Comment by whoteit** [comment]
I confirm it is still happening in the current version. Traces and logs continue working, metrics do not. It automatically recovers on its own after 2-3 hours, or it recovers when restarting the otel-collector or the .NET app exporting the metrics.

On the exporter side, ConsoleExporter continues logging the metrics, but Wireshark shows that only TCP keepalives are being sent on port 4317.

Would switching to HTTP make a difference ?

**Comment by iuribrindeiro** [comment]
Is there any workaround for this? I'm facing this issue for a while now and I just don't knwo what to do besides restarting the application. Which is pretty hard to do during peak times.

**Comment by hartstores** [comment]
@iuribrindeiro 
I switched from gRPC to HTTP and the issue disappeared (the issue was happening every day when I was on gRPC)

**Comment by iuribrindeiro** [comment]
~@hartstores interesting. This was going to be my next attempt. Thx for letting me know!~

**Edit:** Changing from gRPC to HTTP also didn't work. Metrics still stop working after some hours (1 day+ most of the times).

**Comment by iuribrindeiro** [comment]
So, any help here?

**Comment by cijothomas** [comment]
> So, any help here?

Without a repro or logs from the time when a repro occurred, it is very difficult to suggest something. 
Could you get a repro for this? If not, could you gather logs from the machine where you are hitting this issue?

**Comment by martincostello** [comment]
Closing due to a lack of repro. We can re-open if one is provided.
